[profile.default]
src = "contracts"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.12.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
